//
//  InfoViewController.swift
//  ios_employee
//
//  Created by Braelyn Chen on 4/5/19.
//  Copyright © 2019 Braelyn Chen. All rights reserved.
//
import UIKit
class InfoViewController: UIViewController{
    @IBOutlet weak var textScrollView: UIScrollView!
    @IBOutlet weak var textLabel: UILabel!
    var category = ""
    var index = 0
    
    var generalSafety = ["Your safety is your personal responsibility.\n\nAlways follow the correct procedures.\n\nNever take shortcuts.\n\nTake responsibility and clean up if you made a mess.\n\nClean and organize your workspace.\n\nEnsure a clear and easy route to emergency exits and equipment.\n\nBe alert and awake on the job.\n\nBe attentive at all times to your work surroundings.\n\nWhen in doubt, contact your supervisor or manager for instruction, guidance, or training.\n\nNever take risks when it comes to safety.\n\nObey safety signs, stickers, and tags.\n\nTake short breaks when you keep up a repetitive motion for a long period of time, and sit, stand, or walk with good posture.\n\nReport serious injuries immediately to a supervisor and get emergency assistance.\n\nKeep things in perspective. Hazards may be limitless, so focus on the most likely risks first.\n\nStrained backs and sliced fingers may be more popular in your workspace than would the risk of flooding (as in a basement office) or the risk of wild animals cutting loose (as in a zoo).",
                         "Educate everyone in the workplace about the safety requirements and consider posting a list of workplace safety tips. A workplace safety training will help them reduce or eliminate injuries and illnesses from occurring in the workplace.\n\nAlways keep the communication lines open with your co-workers, employers, or employees in order to promote and maintain a safe environment.\n\nImmediately notify others of any (new or old) hazards that you perceive.\n\nBe alert to hazards that could affect anyone— not just yourself; in this respect, maintain a team mentality at all times.\n\nReport a hazardous condition immediately to your manager or supervisor.\n\nBe conscious as to what others are doing around you, and do your best to ensure you don’t pose a hazard to them (and vice versa).\n\nIf you’re an employer, invite and involve your employees in safety planning; obtain their insight, give and take suggestions, and ensure that everyone is on the same page.",
                         "Always use both hands when lifting a heavy or cumbersome object.\n\nAdopt a proper stance for lifting: put the strain on your legs, not your back (crouch at your feet, keep your back straight, and don’t bend at the waist).\n\nTest the weight before you lift something up completely; it might be too late if you realize a few seconds later that it’s too heavy or cumbersome for you.\n\nAn easy way to do this is to nudge it with your foot first.\n\nConsider a back brace if the work is heavy or you have a sensitive back.\n\nMove your feet, not your back, when you want to travel or turn while carrying a heavy load.\n\nLift slowly and smoothly.\n\nKeep your burden close to your body; this means less strain on you.\n\nIf your load is too heavy for you to handle alone, don’t be shy—ask for help!\n\nEnsure ladders are secure and steady before climbing aboard.\n\nNever climb on improvised ladders. Shelves and storage units are poor substitutes. Don’t be lazy, and find a proper solid ladder.\n\nDon’t let appearances fool you. Railings might appear solid and fixed, but they might be improperly secures; at least, test them first.\n\nUse safety harnesses if your job includes heights.\n\nEliminate distractions when working on a roof, scaffold, or other elevated platform. More than ever, stay focused and alert!\n\nKeep an eye out on the floor to ensure it’s free of obstacles and spills. If it isn’t, get cleaning!",
                         "Use machinery only if you’re authorized, trained, and alert.\n\nAlways use the appropriate tool for the respective task.\n\nClean your tools and keep them in good working order.\n\nOrganize your tools and don’t be careless; someone could easily slip or get hit due to a misplaced object.\n\nAlways ensure that the operator of a machine sees you; never approach from behind or from a blind side.\n\nDo not perform a task unless you’ve been trained and you are aware of the hazards as well as how to mitigate/eliminate them.\n\nNever leave machinery running unattended.\n\nNever remove safety guards that are in place to protect you and the surrounding area.\n\nObey all operating instructions.\n\nIf something is wrong, stop the machine immediately and get assistance.\n\nCommunicate your location and process to those around you, so they’ll know where you are, what you’re doing, and when they need to be getting out of the way.\n\nNever walk in front of a forklift, tractor, or any other heavy machine; the operator may not have seen you—and, even if he has, there’s always room for error, so make sure that error isn’t you being trampled.\n\nAlways read labels and instructions alerting you to potential dangers and hazards.\n\nUnless it’s your job, never tamper with electric controls, cords, switches, or other such hazardous items.\n\nDress properly and compactly: billowing, loose, or hanging clothes and accessories (ties, earrings, bracelets, loose sleeves, etc.) may easily get caught up in moving parts.\n\nAt best, the offending objects may be destroyed; at worst, they could ruin the machine or severely hurt you.\n\nNever insert fingers or any other objects that don’t belong into moving machinery.\n\nTurn off machines and equipment before you even consider cleaning, un-jamming, oiling, adjusting, or moving them.",
                         "Come up with a fire emergency plan; ensure that everyone knows and understands it.\n\nPractice fire drills.\n\nAvoid “power strips” which can ignite a fire if overloaded.\n\nVentilation is critical, especially if dealing with fumes and chemicals.\n\nGood ventilation helps to reduce the toxins in the air, and thus to eliminate highly flammable vapors.\n\nIn case of fire, know what has fed the fire.\n\nNever fight a grease fire with water; water will splash the oil and spread the flames.\n\nBe aware of the whereabouts and use of fire extinguishers.",
                         "Always wear appropriate clothing and shoes respective to your job.\n\nFire extinguishers must be available and readily attainable.\n\nFirst aid kits must be available and readily attainable.\n\nNever remove or tamper with safety devices.\n\nUse a back brace if you’re lifting heavy objects or you’ve got a sensitive back.\n\nA hard hat will protect you if there’s a risk of falling objects\n\nWear gloves if you’re handling sharp objects or toxic substances.\n\nWear goggles if your work poses a hazard to your eyes.\n\nWear safety harnesses if you’re working from an elevated location and there’s the risk of falling."]
    
    var health = ["Start your day by eating a wholesome breakfast\n\t\u{2022}Breakfast should be high in protein or fat to sustain your energy until lunch\n\t\u{2022}Avoid a breakfast high in sugar, the calorie intake from sugar tends to burn quickly causing a crash later on\n\t\u{2022}Don’t over-do the coffee- caffeine can also cause a crash later on\n\nSnacking should be high in protein or should be raw foods\n\t\u{2022}Have a high protein snack like nuts or trail mix if you must snack during the day\n\t\u{2022}Avoid greasy, sugary, overly salty, or fried snacks such as chips- these can cause fatigue. Fight the craving!\n\nHave water or a water bottle near you at all times, and drink it as often as possible\n\t\u{2022}Adults need to consume 8 8 ounce glasses of water every day. That’s 64 ounces, and most water bottle are 24-30 Oz. Try and fill it about 3-4 times through the day.\n\t\u{2022}Most offices have a clean, drinkable water source. Use it! Staying hydrated keeps you alert.\n\nMake lunch at home\n\t\u{2022}Making your lunch at home typically helps you choose healthy options, especially if you shop healthy.\n\t\u{2022}Lunch can be quick and easy if you throw a salad together using leftover meats etc, or a sandwich.\n\t\u{2022}Avoid lunch with a lot of starch like breads, pasta, rice, etc. High starch lunches can make you sluggish in the afternoon. Lunch should be light and fresh, to sustain you and your focus for the second half of your workday.\n\t\u{2022}Try to make your lunch at home as often as possible, it’s easier to make bad decisions when getting lunch from somewhere nearby or going out to lunch with coworkers",
                  "Using the above healthy eating tips can help you avoid worktime fatigue. However, due to natural Cicadian Rhythms, adults typically experience bouts of fatigue during 10am-11am and 2pm-3pm.\n\nAvoid caffeine during these times, it might be tempting but it’s a temporary fix and can cause a crash later on\n\t\u{2022}Also, avoid filling these periods with unnecessary snacking\n\nGo for a walk, sit outside or move around somehow\n\t\u{2022}Especially if you have a sedentary desk job, it’s unbelievably important to get up and move around throughout your workday\n\t\u{2022}Step away from the computer. It might be tempting to pop over to social media but get your eyes away from that computer screen for a bit and refocus.\n\t\u{2022}Splash some cold water on your eyes. Cold water opens/expands your blood vessels which increases their energy carrying capacity. It’ll also feel refreshing!\n\t\u{2022}Drink some cold water while you’re at it!\n\t\u{2022}Do some light stretching- this will get the blood pumping to limbs that have been stagnant for a few hours.",
                  "Know the in’s and out’s of workplace ergonomics so your job doesn’t take a toll on your body.\n\t\u{2022}Pay special attention to areas of your body where there is repetitive motion or stress from job functions\n\nGet plenty of rest each night. Adults should get AT LEAST 8 hours of uninterrupted sleep. If you don’t get enough sleep because your thoughts are buzzing, consider talking to a doctor about how you can get plenty of rest.\n\t\u{2022}You’re likely already in a sleeping routine that either works, or does not work for you. Make sure it works- sleep is important. It’s your brain re-setting itself to take on the mental activities of the day ahead. Treat your brain right by allowing it to get the rest it needs.\n\nStop smoking. If you’re a smoker, you’re likely already fully aware of how unhealthy it is for you, and you probably get told all the time to stop by coworkers, friends and family, or even random folks you come into contact with. It’s not them judging you, it’s good advice- take it seriously and stop smoking. It’s hard, but you can’t even fathom how much you increase your health even after one week of no smokes. Trust me on this one."]
    
    var orientation = ["Keep file cabinets closed and secure\n\t\u{2022}Do not stack items on top of file cabinets\n\t\u{2022}Ensure that weight is evenly distributed throughout each drawer\n\t\u{2022}Keep file cabinet drawers closed\n\nPrevent slips, trips, and falls\n\nRemove any empty boxes or items stacked in a way that they may potentially injury someone\n\nKeeps wires, cords, etc. bunched and out of the way of foot traffic\n\nImmediate clean up spills, water, or anything else that could cause a slip\n\nEnsure all emergency exits are free and clear of obstruction\n\nMake sure the exits have the proper exit lights above them in the event of a fire and they cannot be seen in smoke\n\nKnow where the emergency exits are\n\nKeep smoke alarms, emergency lights, security systems fully charged and maintained",
                       "Keep a wide base of support.\n\t\u{2022}Your feet should be shoulder-width apart, with one foot slightly ahead of the other (karate stance).\n\nSquat down,bending at the hips and knees only.\n\nKeep good posture.\n\t\u{2022}Look straight ahead, and keep your back straight, your chest out, and your shoulders back.\n\t\u{2022}This helps keep your upper back straight while having a slight arch in your lower back.\n\nSlowly lift by straightening your hips and knees (not your back).\n\nHold the load as close to your body as possible, at the level of your belly button.\n\nUse your feet to change direction, taking small steps.n\nLead with your hips as you change direction.\n\nSet down your load carefully, squatting with the knees and hips only.",
                       "Buy quality tools.\n\t\u{2022}Many tools, including cutters and hammers, should be made of steel and should be heat-treated.\n\t\u{2022}Regularly inspect tools to make sure they are in good shape and fit for use.\n\t\u{2022}Be sure to maintain your tools by performing regular maintenance, like grinding or sharpening.\n\t\u{2022}Always follow the manufacturer’s instructions.\n\nDress for the job by avoiding loose clothing or articles that can get caught in a tool’s moving parts, like jewelry.\n\nUse the right tool for the job. In other words, don’t try to use a wrench as a hammer.\n\nMake sure that your feet are planted on a stable surface.\n\t\u{2022}Be aware of the people around you and make sure they stay clear of the tools you are using.\n\nNever carry tools up a ladder by hand.\n\t\u{2022}Instead, use a bucket or bag to hoist tools from the ground to the worker.\n\nWhen appropriate, secure work with a clamp or vise to keep it from slipping.\n\nNever carry pointed tools in your pocket. Carry them in a toolbox or cart instead.",
                       "Understand the role of your personal protective equipment (PPE).\n\t\u{2022}Safety glasses protect a worker’s eyes from contact by objects and debris. Wraparound goggles provide side protection and some designs will reduce liquid and vapor penetration.\n\t\u{2022}Laboratory coats, FR apparel, and secondary disposable FR wear offer protection against chemical spills, splashes and arc flash hazards.\n\nGloves should be selected carefully for the types of hazards present of the job.\n\nKnow the situations when PPE should be used.\n\t\u{2022}Following OSHA guidelines is the recommended action for deciding what PPE should be used and when it is required.\n\t\u{2022}In any area where workers face airborne debris, safety glasses must be used. Hard hats are required for construction sites and any environments where workers face the hazard of falling objects. Protective apparel, gloves, boots and masks are required in many different operations including those that involve chemicals and flame / burn hazards.\n\nDesign a PPE program.\n\t\u{2022}Employers are required to provide workers with the tools and safety equipment needed to perform their jobs. Training requirements include knowing when the PPE is needed and what type is required. Employees must understand how to use or wear safety equipment. If it is not used correctly, it does not provide necessary protection. This training program should also include how to inspect equipment and when new PPE should be requested. Checklists should be made available to supervisors and one or more individuals assigned to maintain training records and assurance programs."]
    
    var meeting = ["Does this topic relate to your workplace?\n\t\u{2022}If not, choose another topic.\n\t\u{2022}Topics should be relevant to worker’s daily job activities so they can apply it\n\t\u{2022}Repeat safety meetings on topics that are considered more hazardous than other\n\t\u{2022}These can be annually, semi-annually, quarterly, monthly, etc.\n\nLook up your company rules or policies about this topic.\n\t\u{2022}Incorporating your company policies into your safety meeting topics can help employees refer back to the policy later\n\t\u{2022}Have company policies about specific/relevant topics\n\t\u{2022}Use your company in case studies or examples\n\t\u{2022}Find out about any injuries, accidents or close calls in your company related to this topic.\n\nDo not hand out copies of the Safety Tip until after the meeting. You want workers to contribute their own ideas, not read off the sheet.",
                   "Read Section I to everyone at the meeting.\n\nAsk if anyone has a personal story about this topic.\n\nDiscuss any problems at your workplace related to this topic.\n\nAsk: \"What can we do to solve our problems with (this topic)?\"\n\nAsk: “Have you had any experience with (this topic) here or at other places you’ve worked that might help us work safer here?”\n\nIf the company has rules or procedures around this topic, discuss them now\n\nAsk if there’s anything else anyone wants to mention on this topic.\n\nBefore you close, remind workers how to report any safety problems at your workplace.",
                   "Keep the meeting fun and engaging\n\t\u{2022}Don’t be afraid to show a video clip or funny safety meeting opener to catch attention and drive engagement\n\nIf it’s a more serious topic, use graphic pictures or video clips of injuries to resonate with employees.\n\t\u{2022}Real life examples always help deliver your message\n\t\u{2022}If you’re going to use graphic or gory images of worker injuries, be sure to warn your audience first!\n\nHave your team come up with a safety slogan"]
    
    
    var industries = ["Aircraft maintenance work includes inspection and repair of aircraft structures, coatings, and systems in hangars and on the air field. Good training and work practices ensure aircraft and worker safety.\n\nTall, heavy aircraft make it hard to see people on the ground when maneuvering in the hangar or maintenance area. Watch and communicate with the aircraft operator to avoid caught/crush accidents (getting run over by a tire or colliding with a wing or tail). Never enter the ramp or flightline without permission from the air field controller.\n\nWork at a steady pace. Rushing your work increases aircraft turnaround and accidents. To avoid a fall, watch for ground lines to the aircraft. Well-lit work areas are safer. Watch sharp leading edges like wing tips and pointy antennas, probes, and “Remove Before Flight” flags that stick out from the aircraft. Colliding with hard, sharp surfaces or protrusions causes bumps, bruises, and cuts.\n\nStay inside painted hazard lines and keep clear of aircraft “prop arcs.” Contact with a propeller, rotor, or exposed rotating part can cause severe injuries. Keep hair tied back and avoid loose clothing and jewelry to prevent entanglement with moving parts. Don’t lean on or place your hands or feet near engine intake areas. Keep tools away and pick up debris near the engine. If an engine starts, you could be severely injured, or small items could be turned into projectiles.\n\nTall aircraft require ladders, platforms, and scaffolds to reach work areas. Follow ladder safety guidelines. Use a fall protection harness where required. You may need to work in cramped quarters while performing aircraft maintenance. Evaluate aircraft access areas and job tasks with limited egress and follow confined space procedures if needed.\n\nAircraft chemicals include lubricants, fuels, coating strippers, paints, and solvents. These can be concentrated and contain hazardous materials; use material safety data sheets (MSDS). MSDS explain how to handle chemicals, proper storage and disposal, and the required personal protective equipment (PPE) for safe work. Do not smoke around aircraft maintenance areas where chemicals and fuels are flammable.\n\nFabrication and repair work requires tools such as welding torches, drills, rivets, or grinders. Properly maintain your tools and follow safety procedures. When moving large, bulky aircraft parts and materials, use assistive devices or get help to make the lift safe. Use good ergonomic practices such as frequent 30-second micro-breaks and job task rotation to prevent fatigue and injury.\n\n",
                      "Agricultural workers may be exposed to animals that can transmit diseases.\n\n Zoonotic diseases, or zoonoses, are diseases that can be transmitted from vertebrate animals to humans. Zoonoses are caused by bacteria, protozoa, fungi, viruses, parasites or prions, which are often part of an animal's natural flora (i.e., microorganisms that live in and on the animal) but are able to cause disease in humans. Infections can result from direct contact with animals or their products such as manure or placenta. Direct transmission can also occur through consumption of animal products (e.g., raw meat, raw milk, etc.) or through an animal bite. Humans can also become indirectly infected by contact with contaminated soil, food, or water. Farmers, ranchers, veterinarians, slaughterhouse workers, and other agricultural workers have a higher risk of contracting zoonoses because of their close contact with animals.\n\nSome examples of zoonotic diseases include: Anthrax, Bovine Tuberculosis, Brucellosis, Cryptosporidiosis, Giardiasis, Hantavirus diseases, Leptospirosis, Ovine Chlamydiosis, Psittacosis and Rabies. Outbreaks of avian flu (normally produces a mild disease in aquatic birds), Q fever (a disease common in cattle, sheep and goats), and certain strains of methicillin-resistant Staphylococcus aureus (MRSA) normally restricted to certain animals are recent examples of zoonoses.\n\nArboviruses are infectious agents that are transmitted to humans by arthropods, such as ticks and mosquitos. The recent Zika and West Nile Virus outbreaks are examples of arbovirus outbreaks.\n\nAn agricultural worker's risk of acquiring a zoonotic, arboviral or other animal-borne infection varies with the type of work tasks he or she performs, the kind(s) of animal(s) to which he or she has exposure and the geographic location of the worksite.",
                      "Wear protective gloves: If there’s a risk of toxic paints or other hazardous materials splashing onto your skin, always wear strong protective gloves available from companies like Brosch Direct. These provide an essential protective barrier against harmful materials and can prevent everything from burns to allergic reactions.\n\nWear overalls: Personal protective equipment is of paramount importance in any high-risk job, so if you’re worried about burns from oil or toxic battery fluids, you should also wear tight-fitting overalls. The same applies when using other irritants including spray paints, so don’t take unnecessary risks.\n\nBe visible at all times: In an environment where noisy machinery, clanking metal, roaring engines and loud voices is the norm, you must make yourself as visible as possible to avoid injuries. High-vis vests can quite literally save lives, so be sure to wear one during working hours.\n\nThrow away oily rags: While it can be tempting to stuff an oily rag in your pocket for future use, try not to do this as the oil might seep through your clothes and harm your skin. Instead, place them in a designated ‘oily rag box’ or cupboard so you know exactly where they are when you need one.",
                      "Adjusting Your Chair\n\t\u{2022}Adjust the seat height so your feet are flat on the floor and your knees equal to – or slightly lower than – your hips.\n\t\u{2022}Adjust the back of the chair to a 100° to 110° reclined angle. Make sure your upper and lower back is supported, using a pillow for extra support if necessary.\n\t\u{2022}Adjust your armrests so that your shoulders are down and relaxed. If your armrests are in the way, remove them.\n\t\u{2022}Sit in the chair with your hips positioned as far back as possible. Use a foot rest if your feet don’t touch the floor.\n\nMonitor Placement\n\t\u{2022}Placing your monitor in an appropriate position helps prevent excessive fatigue, eye strain, and neck or back pain.\n\t\u{2022}Center and position the top of the monitor approximately 2 to 3 inches above seated eye level.\n\t\u{2022}Sit at least an arm’s length away from the screen, making adjustments to suit your vision.\n\t\u{2022}You can reduce glare by positioning your screen away from windows, adjusting blinds or using a filter.\n\t\u{2022}Position source documents directly in front of you, between the monitor and the keyboard, using a copy stand.\n\nKeyboard and Mouse Considerations\n\t\u{2022}If your keyboard and mouse are not adjusted properly, it can lead to discomfort in your wrists, arms and shoulders.\n\t\u{2022}Place the keyboard directly in front of you at a distance that allows your elbows to stay close to your body and your forearms approximately parallel with the floor.\n\t\u{2022}Use the keyboard feet to adjust the tilt of your keyboard. If you sit in a forward or upright position, try tilting your keyboard away from you at a negative angle. If you are reclined, a slight positive tilt will help maintain a straight wrist position.\n\t\u{2022}A wrist rest can help you to maintain neutral postures and pad hard surfaces, but resting on it while typing is not recommended.",
                      "Use General SOPs\nEach chemical has a unique set of hazards and needs to be handled properly to ensure worker safety. However, for laboratories that handle a wide variety of chemicals, establishing a separate protocol for each chemical complicates training and increases the likelihood of mishandling and exposure.\nA standard operating procedure (SOP) that addresses the use of correct personal protective equipment, safe handling, safe use, and proper disposal can cover all chemicals in a laboratory. Flip charts, signs, or other literature can then be used to remind workers of specific chemical hazards.\n\nAir Flow\nAir quality can quickly become compromised in laboratories, making ventilation an important factor in minimizing exposure. When determining whether the local exhaust system is adequate, a good rule of thumb is that the system should be capable of at least eight to 10 air changeouts per hour when the space is occupied.\nIn addition to the general exhaust system for the laboratory, exhaust hoods are another tool to increase safety. The National Research Council's Prudent Practices for Handling Hazardous Chemicals in Laboratories recommends \"2.5 linear feet of hood space per person should be provided for every 2 workers if they spend most of their time working with chemicals. Each hood should have a continuous monitoring device to allow convenient confirmation of adequate hood performance before use.\n\nHousekeeping\nKeeping floors clean and dry will help prevent slip and fall injuries -- the third-leading cause of worker injury and lost work time. Stocking absorbent mat pads and wipers in spill-prone locations helps employees clean up spills quickly, so the chance of a slip-and-fall incident is reduced and exposure is minimized. Providing a proper receptacle for spent cleanup materials also helps to minimize exposure.\nCleaning work surfaces throughout the day keeps work spaces uncluttered, decreasing the likelihood of reactions and spills due to counter space being overcrowded. Likewise, storing excess chemicals on countertops should be discouraged so workers will have adequate space to perform their duties properly.",
                      "What Personal Protective Equipment (PPE) to Wear\n\t\u{2022}It’s important that you wear the right clothes for your job, which means wearing protective gear if need be. On the job, you should store your gear and other tools in a safe, dry place. First aid kits and fire extinguishers should be located near the work area and readily available.\n\t\u{2022}If you’re lifting heavy objects, you should use a back brace to prevent damage to your body. You should also be sure to wear gloves and goggles on the worksite if you’re using dangerous tools. If you’re working on an elevated area and there’s a risk of slipping and falling, you should wear a safety harness.\n\t\u{2022}You should also wear nonskid, rubber footwear if you are working in an area with slippery surfaces. Or, if you’re lifting particularly heavy objects. Be sure to find the most comfortable composite toe shoes for work.\n\t\u{2022}It’s crucial to your health that you wear a breathing mask at work if your workplace has bad ventilation if you work with dangerous toxins, or if you deal with constant dust or other debris.\n\nStaying Safe Loading or Unloading Equipment\n\t\u{2022}No matter where you’re working, there’s always the risk of equipment rolling over if you’re loading or unloading it. This is why it’s important to make sure the ramps you’re using are straight and cleared. You should also be sure to allow plenty of room between you and the equipment in case of an emergency.\n\t\u{2022}Make sure you use another co-worker as a spotter while guiding your equipment and make sure the machine is clear of the ramp before turning it. However, you should also make sure the trailer deck and you have proper clearance before loading it, in addition to using correct tie-down procedures.\n\nCrowded Work Areas\n\t\u{2022}When it comes to construction workplace frustrations, crowding in work areas is one of the biggest. This is especially an issue with large machinery. People on the work site gather to watch the large machines work. Usually, there is no reason for this; it is just a habit. However, it increases unnecessary exposure to injury.\n\t\u{2022}If someone is working with large machinery, people on the ground should remain far from the operating area. Foremen should enforce this rule and review it at any safety meetings. It is not the operator’s responsibility to ensure people stay back while they are trying to work. However, they can beep their horn to warn others when they are about to begin working. They should also be sure to check closely behind them when they are backing up.",
                      "Inform Supervisors of Unsafe Conditions:\nIf you see something that could potentially hurt someone, remove the object or clean the area if you can do so safely. Otherwise, inform your supervisor. Since your supervisor is legally obligated to keep you and your fellow employees’ working environment safe, they must take action.\n\nUse Equipment, Machines, and Tools Properly:\nMisusing tools and machines is the most prevalent cause of workplace injuries. When using equipment, make sure that you are using each piece of equipment for its intended purpose and are using it correctly. Furthermore, regularly clean and inspect equipment to ensure that it is safe.\n\nWear Safety Equipment (PPE):\nWhen cleaning up messes and using equipment, make sure you wear the proper safety equipment. Making sure you wear the proper safety equipment and checking that your safety equipment is undamaged significantly lowers your likelihood of getting injured.\n\nPrevent Slips and Trips:\nAs the second most prevalent cause of nonfatal occupational injuries, it is vital to ensure that aisles are clear and spills are cleaned to prevent employees from tripping or slipping. If you are dealing with a liquid, use drip pans and guards. Clean up any spills immediately to keep conditions safe. Also, check your workplace to make sure there are no holes, loose boards, or nails projecting from the floor. If any of these characteristics exist, replace the damaged flooring. In areas that cannot easily be cleaned, consider installing anti-slip flooring.",
                      "Never assume the power circuit is off. Test and test again with a voltmeter to confirm.\n\nRemove fuses and replace them only after the power to the circuit is disconnected.\n\nDon’t connect power to a circuit until you’re done working on it and rechecked the work.\n\nAlways ensure that all electronics equipment is properly grounded\n\nIf it’s damaged, replace it. For instance, replace cables instead of repairing with insulating tape.\n\nAlways use the right electronics repair and maintenance tools.\n\nAlways return covers after removing them to reduce the risk of electric shock.\n\nMake sure your circuit is not overloaded.\n\nAlways have safety equipment like a fire extinguisher, a basic first aid kit and a mobile phone nearby.\n\n Always keep your work area dry.\n\nlways work in a well-ventilated area.\n\nDon’t wear flapping or loose clothing when working.\n\nDon’t work with metallic jewelry on your hands like watches, rings and bracelets.\n\nDon’t use bare hands to remove hot parts. ",
                      "Take Precautions in order to avoid Bloodborne Pathogens:\nHealth care staff often come in contact to patients’ body liquids and it is subjected to bloodborne pathogens. In cases like this, bacterial and viral microbe infections are communicated through bloodstream and other body essential fluids. Moreover, through way, the chance for infection boosts when a staff member touches these fluids. Healthcare staff should therefore take necessary safeguards and wear personal protecting equipment to avoid the infection. Proper wear of gowns, gloves, basic safety goggles, and face shields keep the body fluids away from the worker’s skin.\nThe medical center/health care center must ensure proper management of exposures and reduce/destroy the existence of infection-causing microorganisms within the service.\n\nUse Proper Devices to decrease the risk of Musculoskeletal Injuries:\nMusculoskeletal injuries are normal with doctors who lift up immobile patients and/or transfer them between bedrooms and wheelchairs. This put those employees in danger for musculoskeletal disorders, who have injury at their bone fragments, muscles, ligaments, nerves, bones, cartilage, tendons, or arteries in the trunk, limbs, throat or head.\nTo keep safe yourself from musculoskeletal disorders and severe aches, use assistive devices such as slide bed linens, slings, and digital hoists whenever you can. Unless you get access to such devices, at least use the right body techniques for reducing the chance of accident; for example, maintain your feet aside and legs bent when raising an immobile patient.",
                      "Be Alert. Know everything going on around you. Always look well ahead down the road and around your rig. When rolling down the highway, especially in heavy traffic, always plan an ‘escape route’. Be aware of who’s in front of you, beside you and behind you at all times. Be aware of everything, so you can act accordingly, if and when necessary.  Being well rested keeps you at your best. The electronic logbook system potentially provides a system for drivers to be well rested, IF utilized properly by the carrier.\n\nCheck Weather Reports. Be aware of weather conditions prior to departing on a trip, and check the reports as often as you’re able while traveling. Keep an eye on your outside temperature to watch for changing road conditions. Knowing what to expect helps a trucker be better prepared for bad weather driving and necessary precautions can be taken. (Part of good trip planning)\n\nAvoid Traffic. Whenever possible, avoid traveling at high volume traffic and peak traffic times. The more traffic, the greater the odds of an accident."
        
    ]
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        textScrollView.layer.cornerRadius = 30
        textScrollView.layer.masksToBounds = true
        textLabel.textColor = UIColor.white
        
        if textScrollView.contentOffset.x>0 {
            textScrollView.contentOffset.x = 0
        }
        
        switch category {
        case "General Workplace Safety":
            textLabel.text = generalSafety[index]
        case "Employee Health Tips":
            textLabel.text = health[index]
        case "Safety Orientation Tips":
            textLabel.text = orientation[index]
        case "Safety Meeting Tips":
            textLabel.text = meeting[index]
        case "Aerospace":
            textLabel.text = industries[0]
        case "Agriculture":
            textLabel.text = industries[1]
        case "Automotive":
            textLabel.text = industries[2]
        case "Banking":
            textLabel.text = industries[3]
        case "Chemical":
            textLabel.text = industries[4]
        case "Computer Software":
            textLabel.text = industries[3]
        case "Commerical":
            textLabel.text = industries[6]
        case "Construction":
            textLabel.text = industries[5]
        case "Education":
            textLabel.text = industries[3]
        case "Electronics":
            textLabel.text = industries[7]
        case "Finance":
            textLabel.text = industries[3]
        case "Government":
            textLabel.text = industries[3]
        case "Health":
            textLabel.text = industries[8]
        case "Transportation":
            textLabel.text = industries[9]
        default:
            print("no topic matches")
        }
    }
    
    @IBAction func dimissButton(_ sender: Any) {
        dismiss(animated: true, completion: nil)
    }
    
    /*
     // MARK: - Navigation
     // In a storyboard-based application, you will often want to do a little preparation before navigation
     override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
     // Get the new view controller using segue.destination.
     // Pass the selected object to the new view controller.
     }
     */
}
